[versions]
gradle-plugin = "7.2.1"
kotlin = "1.6.21"
lifecycle = "2.5.1"
core_ktx = "1.8.0"
appcompat = "1.4.2"
material = "1.6.1"
gradleplugin = "7.2.1"
constraintlayout = "2.1.4"
junit = "4.9.0"
junit-android = "1.1.3"
junit-android-core = "3.4.0"
activity-ktx = "1.5.1"
coroutine = "1.6.4"
coroutinesLifeScope = "2.5.1"
roomVersion = "2.4.1"
recyclerview = "1.2.1"
fragementKtx = "1.5.3"
moduleDependency = "2.3.0"
hancrestVersion = "1.3"
androidTestCore = "2.1.0"
coroutinesTest = "1.2.1"
truth-test = "1.0.1"
navVersion = "2.5.3"
wearableVersion="18.0.0"
percentLayoutVersion="1.0.0"
wearOsVersion="1.2.0"
legacyVersionSupport="1.0.0"
hiltVersion = "2.44"


[libraries]
percent-layout={module="androidx.percentlayout:percentlayout", version.ref="percentLayoutVersion"}
wearable={module="com.google.android.gms:play-services-wearable", version.ref="wearableVersion"}
wearOs={module="androidx.wear:wear", version.ref="wearOsVersion"}
legacy-lib= { module="androidx.legacy:legacy-support-v4", version.ref="legacyVersionSupport"}
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navVersion" }
navigation-fragment-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navVersion" }
navigation-fragment-dynamicFeatures = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navVersion" }
navigation-safe-args={module="androidx.navigation:navigation-safe-args-gradle-plugin", version.ref="navVersion"}
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragementKtx" }
hamcrest-test = { module = "org.hamcrest:hamcrest-all", version.ref = "hancrestVersion" }
android-test-core = { module = "androidx.arch.core:core-testing", version.ref = "androidTestCore" }
coroutineTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }
truth-test = { module = "com.google.truth:truth", version.ref = "truth-test" }
coroutine-ktx = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
coroutines-lifeScope-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "coroutinesLifeScope" }
coroutines-lifeScope-runTime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "coroutinesLifeScope" }
testCoroutines = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutine"}
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
dagger-android = {module = "com.google.dagger:hilt-android", version.ref = "hiltVersion"}
dagger-compiler = {module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltVersion"}

junit = { module = "junit:junit", version.ref = "junit" }
junit-android = { module = "androidx.test.ext:junit", version.ref = "junit-android" }
junit-android-core = { module = "androidx.test.espresso:espresso-core", version.ref = "junit-android-core" }

recyclerViewDependency = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }


[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "gradle-plugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
moduleDependency = { id = "com.jraska.module.graph.assertion", version.ref = "moduleDependency" }
dagger-hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion"}

[bundles]
android-core = ["androidx-core-ktx", "appcompat", "material", "constraintlayout"]
lifecycle = ["viewmodel-ktx", "livedata-ktx", "runtime-ktx"]
junit-android = ["junit-android", "junit-android-core"]